Restore workflows

diff --git a/.github/workflows/maven_build_deploy.yml b/.github/workflows/maven_build_deploy.yml
--- a/.github/workflows/maven_build_deploy.yml
+++ b/.github/workflows/maven_build_deploy.yml
@@ -30,25 +30,42 @@ jobs:
             echo "Git clone llama.cpp failed."
             exit 1
           fi
-
-          cp -r llamajava llama.cpp
+          
+          cp llamajava/* llama.cpp
           cd llama.cpp
           LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
           echo "=> Llama.cpp latest tag: $LATEST_TAG"
           git checkout $LATEST_TAG
-          echo "add_subdirectory(llamajava)">>CMakeLists.txt
           echo "=> Checkout llama.cpp $LATEST_TAG finished."
 
-      - name: Build
-        id: cmake_build
+      - name: Update MakeFile
+        id: makefile
         shell: bash
         run: |
           cd llama.cpp
-          mkdir build
-          cd build
-          cmake .. -DLLAMA_NATIVE=OFF -DLLAMA_BLAS=ON -DBUILD_SHARED_LIBS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS 
-          cmake --build . --config Release
-          if [ -f "llamajava/libllama_java.so" ]; then
+          if [ ! -f "llamajava.cpp" ]; then
+            echo "llamajava.cpp not found"
+            exit 1
+          fi
+
+          if [ ! -f "Makefile_backup" ]; then
+            cp "Makefile" "Makefile_backup"
+          fi
+
+          BUILD_LLAMA_JAVA_CMD="llamajava.o: llamajava.cpp llamajava.h jni.h jni_md.h \n\t\$(CXX) \$(CXXFLAGS) -c $< -o \$@\n"
+          LIB_LLAMA_CMD="libllama.so: llama.o ggml.o \$(OBJS)"
+          BUILD_LLAMA_JAVA_SO_CMD="$BUILD_LLAMA_JAVA_CMD\nlibllama.so: llama.o ggml.o grammar-parser.o llamajava.o \$(OBJS)"
+          echo $BUILD_LLAMA_JAVA_SO_CMD
+          sed -i "s/$LIB_LLAMA_CMD/$BUILD_LLAMA_JAVA_SO_CMD/g" "Makefile"
+
+      - name: Build
+        id: make_build
+        shell: bash
+        run: |
+          cd llama.cpp
+          make clean
+          make LLAMA_OPENBLAS=1 libllama.so
+          if [ -f "libllama.so" ]; then
             ls -l
             echo "Build libllama.so success"
           fi
@@ -57,7 +74,7 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: linux-libllama
-          path: llama.cpp/build/llamajava/libllama_java.so
+          path: llama.cpp/libllama.so
 
   #build macos lib
   build-macos-lib:
@@ -76,25 +93,42 @@ jobs:
             echo "Git clone llama.cpp failed."
             exit 1
           fi
-
-          cp -r llamajava llama.cpp
+          
+          cp llamajava/* llama.cpp
           cd llama.cpp
           LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
           echo "=> Llama.cpp latest tag: $LATEST_TAG"
           git checkout $LATEST_TAG
-          echo "add_subdirectory(llamajava)">>CMakeLists.txt
           echo "=> Checkout llama.cpp $LATEST_TAG finished."
 
-      - name: Build
-        id: cmake_build
+      - name: Update MakeFile
+        id: makefile
         shell: bash
         run: |
           cd llama.cpp
-          mkdir build
-          cd build
-          cmake .. -DLLAMA_NATIVE=OFF -DLLAMA_BLAS=ON -DBUILD_SHARED_LIBS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS 
-          cmake --build . --config Release
-          if [ -f "llamajava/libllama_java.dylib" ]; then
+          if [ ! -f "llamajava.cpp" ]; then
+            echo "llamajava.cpp not found"
+            exit 1
+          fi
+
+          if [ ! -f "Makefile_backup" ]; then
+            cp "Makefile" "Makefile_backup"
+          fi
+          
+          BUILD_LLAMA_JAVA_CMD="llamajava.o: llamajava.cpp llamajava.h jni.h jni_md.h \n\t\$(CXX) \$(CXXFLAGS) -c $< -o \$@\n"
+          BUILD_LLAMA_JAVA_DYLIB_CMD="$BUILD_LLAMA_JAVA_CMD\nlibllama.dylib: llama.o ggml.o grammar-parser.o llamajava.o \$(OBJS) \n\t\$(CXX) \$(CXXFLAGS) -shared -fPIC -o \$@ $^ \$(LDFLAGS)\n"
+          BUILD_LLAMA_CMD="$BUILD_LLAMA_JAVA_DYLIB_CMD\nclean:"
+          echo $BUILD_LLAMA_CMD
+          sed -i "" -e "s/clean:/$BUILD_LLAMA_CMD/g" "Makefile"
+
+      - name: Build
+        id: make_build
+        shell: bash
+        run: |
+          cd llama.cpp
+          make clean
+          make libllama.dylib
+          if [ -f "libllama.dylib" ]; then
             ls -l
             echo "Build libllama.dylib success"
           fi
@@ -103,7 +137,7 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: macos-libllama
-          path: llama.cpp/build/llamajava/libllama_java.dylib
+          path: llama.cpp/libllama.dylib
 
   #build windows lib
   build-windows-lib:
